/* Désactiver temporairement les contraintes FK */
EXEC sp_msforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT ALL";

DROP TABLE IF EXISTS tmp_employee;
DROP TABLE IF EXISTS notification_recipients;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS prevision_price;
DROP TABLE IF EXISTS logs;
DROP TABLE IF EXISTS mission_comments;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS mission_report_attachments;
DROP TABLE IF EXISTS mission_report;
DROP TABLE IF EXISTS expense_report_attachments;
DROP TABLE IF EXISTS expense_report;
DROP TABLE IF EXISTS mission_budget;
DROP TABLE IF EXISTS mission_validation;
DROP TABLE IF EXISTS compensation;
DROP TABLE IF EXISTS mission_assignation;
DROP TABLE IF EXISTS compensation_scale;
DROP TABLE IF EXISTS expense_compensation_scale;
DROP TABLE IF EXISTS employee_nationalities;
DROP TABLE IF EXISTS user_habilitations;
DROP TABLE IF EXISTS role_habilitation;
DROP TABLE IF EXISTS user_availability; 
DROP TABLE IF EXISTS user_role;
DROP TABLE IF EXISTS categories_of_employee;
DROP TABLE IF EXISTS mission;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS units;
DROP TABLE IF EXISTS service;
DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS menu_hierarchy;
DROP TABLE IF EXISTS menu_role;
DROP TABLE IF EXISTS menu;
DROP TABLE IF EXISTS module;
DROP TABLE IF EXISTS direction;
DROP TABLE IF EXISTS site;
DROP TABLE IF EXISTS lieu;
DROP TABLE IF EXISTS geo_zones;
DROP TABLE IF EXISTS transport;
DROP TABLE IF EXISTS expense_type;
DROP TABLE IF EXISTS expense_report_type;
DROP TABLE IF EXISTS habilitations;
DROP TABLE IF EXISTS habilitation_groups;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS employee_categories;
DROP TABLE IF EXISTS contract_types;
DROP TABLE IF EXISTS genders;
DROP TABLE IF EXISTS nationalities;

DROP TABLE IF EXISTS comments_candidatures;
DROP TABLE IF EXISTS tests;
DROP TABLE IF EXISTS evaluations;
DROP TABLE IF EXISTS candidatures;
DROP TABLE IF EXISTS skills;
DROP TABLE IF EXISTS jobs_suitabilities;
DROP TABLE IF EXISTS experiences;
DROP TABLE IF EXISTS formations;
DROP TABLE IF EXISTS jobs_validations;
DROP TABLE IF EXISTS Attributions;
DROP TABLE IF EXISTS job_descriptions;
DROP TABLE IF EXISTS requests_validations;
DROP TABLE IF EXISTS sites_requests;
DROP TABLE IF EXISTS recruitment_requests;
DROP TABLE IF EXISTS evaluation_types;
DROP TABLE IF EXISTS personnal_suitabilities;
DROP TABLE IF EXISTS educations;
DROP TABLE IF EXISTS level_educations;
DROP TABLE IF EXISTS job_descriptions_status;
DROP TABLE IF EXISTS requests_status;
DROP TABLE IF EXISTS replacement_reasons;

/* Réactiver les contraintes FK */
EXEC sp_msforeachtable "ALTER TABLE ? WITH CHECK CHECK CONSTRAINT ALL";
